/* eslint-disable unicorn/no-Number.NaN */
import type { Meta, StoryObj } from '@storybook/react';
import { scaleLinear } from 'd3-scale';
import AreaGraph from 'features/charts/elements/AreaGraph';
import { getFills } from 'features/charts/hooks/usePriceChartData';
import { AreaGraphElement } from 'features/charts/types';
import { TimeAverages } from 'utils/constants';

const meta: Meta<typeof AreaGraph> = {
  title: 'charts/BreakdownChart',
  component: AreaGraph,
};

type Story = StoryObj<typeof AreaGraph>;

const chartData = [
  {
    datetime: '2022-11-26T19:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 211.7 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0,
    },
  },
  {
    datetime: '2022-11-26T20:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 209.11 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0,
    },
  },
  {
    datetime: '2022-11-26T21:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 216.37 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0,
    },
  },
  {
    datetime: '2022-11-26T22:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 235.88 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0,
    },
  },
  {
    datetime: '2022-11-26T23:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 234.69 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0,
    },
  },
  {
    datetime: '2022-11-27T00:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 236.59 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0,
    },
  },
  {
    datetime: '2022-11-27T01:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 241.84 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0,
    },
  },
  {
    datetime: '2022-11-27T02:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 248.89 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0,
    },
  },
  {
    datetime: '2022-11-27T03:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 269.73 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0,
    },
  },
  {
    datetime: '2022-11-27T04:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 279.84 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0,
    },
  },
  {
    datetime: '2022-11-27T05:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 276.79 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0,
    },
  },
  {
    datetime: '2022-11-27T06:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 246.3 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0,
    },
  },
  {
    datetime: '2022-11-27T07:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 250.96 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0,
    },
  },
  {
    datetime: '2022-11-27T08:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 246.4 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0,
    },
  },
  {
    datetime: '2022-11-27T09:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 241.27 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0,
    },
  },
  {
    datetime: '2022-11-27T10:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 160.78 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0.084,
    },
  },
  {
    datetime: '2022-11-27T11:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 220.16 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0,
    },
  },
  {
    datetime: '2022-11-27T12:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 208.28 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0,
    },
  },
  {
    datetime: '2022-11-27T13:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 217.58 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0,
    },
  },
  {
    datetime: '2022-11-27T14:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 240.4 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0,
    },
  },
  {
    datetime: '2022-11-27T15:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 229.55 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0,
    },
  },
  {
    datetime: '2022-11-27T16:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 193.86 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0,
    },
  },
  {
    datetime: '2022-11-27T17:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 173.79 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0,
    },
  },
  {
    datetime: '2022-11-27T18:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 165.63 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0,
    },
  },
  {
    datetime: '2022-11-27T19:00:00.000Z',
    meta: { exchangeCo2Intensities: { ES: 162.37 } },
    layerData: {
      nuclear: Number.NaN,
      geothermal: Number.NaN,
      biomass: Number.NaN,
      coal: Number.NaN,
      wind: Number.NaN,
      solar: Number.NaN,
      hydro: Number.NaN,
      'hydro storage': 0,
      'battery storage': 0,
      gas: Number.NaN,
      oil: Number.NaN,
      unknown: Number.NaN,
      ES: 0,
    },
  },
].map((d) => ({ ...d, datetime: new Date(d.datetime) }));

const includesStorageData = [...chartData];

export const IncludesStorage: Story = {
  // More on args: https://storybook.js.org/docs/react/writing-stories/args
  args: {
    testId: 'none',
    data: includesStorageData,
    layerKeys: Object.keys(includesStorageData[0].layerData),
    layerStroke: undefined,
    layerFill: getFills(includesStorageData).layerFill,
    markerFill: getFills(includesStorageData).markerFill,
    selectedTimeAggregate: TimeAverages.HOURLY,
    valueAxisLabel: '€ / MWh',
    isMobile: false,
    height: '12em',
    datetimes: chartData.map((d) => d.datetime),
  },
};

export default meta;
