bounding_box:
  - - -8.144154425999943
    - 60.894110419000086
  - - -5.775786912999905
    - 62.89891185100005
capacity:
  biomass: 1.3
  hydro: 40.6
  oil: 99.7
  solar: 0.24
  unknown: 0.1
  wind: 43.5
contributors:
  - corradio
  - q--
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 472.2080162959618
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 453.019270473374
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 522.0839264192048
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 544.3573263700255
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 538.8952236011929
    gas:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 481.60707
    hydro discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 472.2080162959618
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 453.019270473374
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 522.0839264192048
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 544.3573263700255
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 538.8952236011929
    oil:
      datetime: '2021-01-01'
      source: EU-ETS, ENTSO-E 2021
      value: 880.903938
    unknown:
      source: Tidal (IPCC 2014)
      value: 0
  lifecycle:
    battery discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 357.4756190182087
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 343.635256065452
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 393.25064707281933
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 409.3641592249868
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 408.8110193788959
    hydro discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 357.4756190182087
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 343.635256065452
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 393.25064707281933
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 409.3641592249868
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 408.8110193788959
    unknown:
      source: Tidal (IPCC 2014)
      value: 17
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 0.2685630274166093
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.6178784421667692
        solar: 0.0
        unknown: 0.0
        wind: 0.1133928104338448
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.01733172985203319
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 0.237708660836947
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.6117476901021067
        solar: 0.0004114547212078257
        unknown: 1.4446059177202655e-05
        wind: 0.13272450542005115
isLowCarbon:
  unknown:
    value: 1
isRenewable:
  unknown:
    value: 1
parsers:
  production: FO.fetch_production
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
subZoneNames:
  - FO-MI
  - FO-SI
timezone: Atlantic/Faroe
