on:
  workflow_call:

jobs:
  jest-test:
    name: Jest tests
    runs-on: ubuntu-latest
    timeout-minutes: 4
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'yarn'
          cache-dependency-path: web/yarn.lock
      - name: Restore node_modules
        id: cache
        uses: actions/cache@v3
        with:
          path: ./web/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('./web/yarn.lock') }}
      - name: Install web dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Generate zone config
        if: steps.cache.outputs.cache-hit == 'true'
        run: yarn generate-zones-config
      - name: Run test
        run: yarn run test
