name: Prettier

on:
  workflow_call:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup Node v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: 'web/pnpm-lock.yaml'
      # - name: Restore node_modules for web
      #   id: cache-web
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       web/node_modules
      #     key: ${{ runner.os }}-node_modules-${{ hashFiles('./web/yarn.lock') }}
      - name: Install web dependencies
        # if: steps.cache-web.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile
        working-directory: ./web
      - name: Prettier Check
        # Uses the prettier binary from the web node_modules so it's always in sync.
        run: |
          web/node_modules/.bin/prettier --check .
